### PR TITLE
v1.0.6

### PR DESCRIPTION
**Pull request by boxdrop**
Fixed PrestaShopClour error

### CODE REVIEW

**Comment by gaillafr** [comment]
Hi @boxdrop, what are you trying to do with this PR?

Thank you, kind regards.

**Comment by boxdrop** [comment]
@gaillafr As we are relying on a proper admin context for some BO AJAX calls, we needed to adjust those includes for the PrestaShop Cloud environment, where die admin subfolder (in this case /backoffice/) is not directly reachable via the instances' root folder. As at those early stages _PS_HOST_MODE_ is not defined yet, we added also a method to detect PrestaShopCloud instances by the environment.

**Comment by gaillafr** [comment]
Did you try directly with?

``` php
_PS_ROOT_DIR_.'/backoffice' 
```

**Comment by boxdrop** [comment]
No, as by the time we need to construct the path for including the config.inc those defines are not yet initialized. 
Basically we are doing adminfolder/index.php lines 28 - 35 (v1.6.0.11 regular installation) in ajax/ajax.php 33 - 49

**Comment by boxdrop** [comment]
@gaillafr bump

**Comment by gaillafr** [comment]
Hi @boxdrop, it looks like you should be able to load the config file the same way:

``` php
require_once (_PS_ROOT_DIR_.'/config/config.inc.php');
```

Thank you,
Kind regards.

**Comment by boxdrop** [comment]
@gaillafr sadly its not working. Plus, its not about the config.php we made that changes, but to define _PS_ADMIN_DIR_ to get an admin context.

**Comment by Quetzacoalt91** [comment]
Hi @boxdrop,

Do not forget to update the file config.xml

Best regards

**Comment by boxdrop** [comment]
Hi @Quetzacoalt91 

I thought this was a configuration cache file generated by the Shop itself? Shall we however create one bundled with the module?

Cheers,

**Comment by Quetzacoalt91** [comment]
It can be generated, but we actually put it directly in the repository. You can see it in the current master branch in example. We bundle it in order to use directly the cache system.

Best regards

**Comment by boxdrop** [comment]
HI @Quetzacoalt91 added the file!

**Comment by Quetzacoalt91** [comment]
Hi @boxdrop,

Thanks, your PR has just been merged and the changes should be available from tomorrow.

Best regards

**Pull request merged**
