### PR TITLE
New pictograms

### PR DESCRIPTION
**Pull request by mathieuesteban**

### CODE REVIEW

**Comment by Quetzacoalt91** [comment]
Hi,

Are you sure about this PR ? The content doesn't fit the official logo of Boxdrop.

**Comment by boxdrop** [comment]
For us its okay.

**Comment by Quetzacoalt91** [comment]
Thanks @boxdrop for your message.

@mathieuesteban, we just have to reduce the logo.png to 57x57 px and we are good to go.

**Comment by mathieuesteban** [comment]
Done

**Pull request merged**
